#!/bin/bash
# Windows MPV build script (MSYS2 version)
# Used to build Windows version of libmpv.a in MSYS2 CLANG64 environment

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
GRAY='\033[0;37m'
NC='\033[0m' # No Color

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR"
MPV_DIR="$PROJECT_ROOT/mpv"
BUILD_DIR="$MPV_DIR/build"
VENDOR_DIR="$PROJECT_ROOT/vendor/mpv/win32-x64"

echo -e "${CYAN}========================================${NC}"
echo -e "${CYAN}Windows MPV Build Script (MSYS2)${NC}"
echo -e "${CYAN}========================================${NC}"
echo ""

# Check if running in MSYS2 environment
if [[ -z "$MSYSTEM" ]]; then
    echo -e "${RED}Error: Please run this script in an MSYS2 terminal${NC}"
    echo -e "${YELLOW}Recommended: MSYS2 CLANG64 or UCRT64${NC}"
    exit 1
fi

# Check and prompt for dependency installation
if ! command -v meson &> /dev/null || ! command -v ninja &> /dev/null; then
    echo -e "${YELLOW}Build tools not detected, please install dependencies first:${NC}"
    echo ""
    echo -e "${CYAN}Installation commands:${NC}"
    echo -e "${GRAY}  pacman -S pactoys git${NC}"
    echo -e "${GRAY}  pacboy -S python pkgconf cc meson ninja${NC}"
    echo -e "${GRAY}  pacboy -S ffmpeg libjpeg-turbo libplacebo luajit vulkan-headers${NC}"
    echo ""
    read -p "Install now? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Installing base tools...${NC}"
        pacman -S --needed pactoys git

        echo -e "${YELLOW}Installing build tools...${NC}"
        pacboy -S --needed python pkgconf cc meson ninja

        echo -e "${YELLOW}Installing mpv dependencies...${NC}"
        pacboy -S --needed ffmpeg libjpeg-turbo libplacebo luajit vulkan-headers

        echo -e "${GREEN}Dependency installation complete!${NC}"
        echo ""
    else
        echo -e "${YELLOW}Please manually install dependencies and re-run the script${NC}"
        exit 1
    fi
fi

# Check mpv directory
if [ ! -d "$MPV_DIR" ]; then
    echo -e "${RED}Error: mpv directory does not exist: $MPV_DIR${NC}"
    echo -e "${YELLOW}Please run: git submodule update --init --recursive${NC}"
    exit 1
fi

# Check if Meson is installed
if ! command -v meson &> /dev/null; then
    echo -e "${RED}Error: meson command not found${NC}"
    echo -e "${YELLOW}Please install: pacboy -S meson${NC}"
    exit 1
fi

# Check if Ninja is installed
if ! command -v ninja &> /dev/null; then
    echo -e "${RED}Error: ninja command not found${NC}"
    echo -e "${YELLOW}Please install: pacboy -S ninja${NC}"
    exit 1
fi

echo -e "${YELLOW}Current environment: $MSYSTEM${NC}"
echo -e "${YELLOW}Entering mpv directory...${NC}"
cd "$MPV_DIR"

# Create subprojects directory (if it does not exist)
if [ ! -d "subprojects" ]; then
    echo -e "${YELLOW}Creating subprojects directory...${NC}"
    mkdir -p subprojects
fi

# Update Meson wrap database
echo ""
echo -e "${YELLOW}Updating Meson wrap database...${NC}"
if ! meson wrap update-db 2>&1; then
    echo -e "${YELLOW}Warning: WrapDB connection failed, trying --allow-insecure...${NC}"
    meson wrap update-db --allow-insecure || {
        echo -e "${YELLOW}Hint: If it keeps failing, you can skip this step${NC}"
    }
fi

# Install required wraps (optional, as MSYS2 already provides dependencies)
echo ""
echo -e "${YELLOW}Installing required Meson wraps (if needed)...${NC}"
wraps=("expat" "harfbuzz" "libpng" "zlib")
for wrap in "${wraps[@]}"; do
    echo -e "${GRAY}  Installing $wrap...${NC}"
    if ! meson wrap install "$wrap" 2>&1 | grep -v "^$"; then
        echo -e "${YELLOW}  Trying --allow-insecure to install $wrap...${NC}"
        meson wrap install "$wrap" --allow-insecure 2>&1 | grep -v "^$" || {
            echo -e "${GRAY}  $wrap may already be installed via system package manager, skipping${NC}"
        }
    fi
done

# Parse command line arguments
LIBRARY_TYPE="static"
USE_LOCAL_DEPS=false
for arg in "$@"; do
    case "$arg" in
        --shared|-s)
            LIBRARY_TYPE="shared"
            ;;
        --local-deps|-l)
            USE_LOCAL_DEPS=true
            ;;
    esac
done

if [ "$LIBRARY_TYPE" == "shared" ]; then
    echo -e "${YELLOW}Building in shared library mode${NC}"
else
    echo -e "${YELLOW}Building in static library mode (use --shared to build dynamic library)${NC}"
fi

# Locally built dependencies directory (generated by build_deps_windows.sh)
LOCAL_DEPS_DIR="$PROJECT_ROOT/deps/win64"
if [ "$USE_LOCAL_DEPS" == true ]; then
    if [ -d "$LOCAL_DEPS_DIR/lib/pkgconfig" ]; then
        echo -e "${GREEN}Using locally built dependencies: $LOCAL_DEPS_DIR${NC}"
        export PKG_CONFIG_PATH="$LOCAL_DEPS_DIR/lib/pkgconfig:$LOCAL_DEPS_DIR/share/pkgconfig:${PKG_CONFIG_PATH:-}"
        export PKG_CONFIG_LIBDIR="$LOCAL_DEPS_DIR/lib/pkgconfig:$LOCAL_DEPS_DIR/share/pkgconfig:${MSYSTEM_PREFIX}/lib/pkgconfig:${MSYSTEM_PREFIX}/share/pkgconfig"
        export PATH="$LOCAL_DEPS_DIR/bin:$PATH"
    else
        echo -e "${RED}Error: Local dependency directory does not exist: $LOCAL_DEPS_DIR${NC}"
        echo -e "${YELLOW}Please run: ./build_deps_windows.sh${NC}"
        exit 1
    fi
fi

# Use CLANG64 toolchain
export CC=clang
export CXX=clang++

# Allow meson's header detection to find local dependencies (e.g. vulkan headers)
if [ "$USE_LOCAL_DEPS" == true ] && [ -d "$LOCAL_DEPS_DIR/include" ]; then
    export CFLAGS="${CFLAGS:-} -I$LOCAL_DEPS_DIR/include"
    export LDFLAGS="${LDFLAGS:-} -L$LOCAL_DEPS_DIR/lib"
fi

# Configure build
echo ""
if [ "$LIBRARY_TYPE" == "shared" ]; then
    echo -e "${YELLOW}Configuring MPV build (shared library)...${NC}"
else
    echo -e "${YELLOW}Configuring MPV build (static library)...${NC}"
fi

# Build arguments
WRAP_MODE="forcefallback"
if [ "$USE_LOCAL_DEPS" == true ]; then
    WRAP_MODE="default"
fi

MESON_ARGS=(
    "setup"
    "build"
    "--wrap-mode=$WRAP_MODE"
    "-Ddefault_library=$LIBRARY_TYPE"
    "-Dlibmpv=true"
    "-Dcplayer=false"
    "-Dtests=false"
    "-Dgpl=true"
    "-Dd3d11=enabled"
    "-Dvulkan=enabled"
    "-Djavascript=disabled"
    "-Dwin32-smtc=disabled"
    "-Dlua=disabled"
    "-Ddrm=disabled"
    "-Dlibarchive=disabled"
    "-Drubberband=disabled"
    "-Dwayland=disabled"
    "-Dx11=disabled"
    "--prefix=$MSYSTEM_PREFIX"
    "--buildtype=release"
    "--strip"
)

# If build directory exists, reconfigure
if [ -d "$BUILD_DIR" ]; then
    echo -e "${GRAY}  Reconfiguring existing build directory...${NC}"
    MESON_ARGS+=("--reconfigure")
fi

meson "${MESON_ARGS[@]}"

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Meson configuration failed${NC}"
    exit 1
fi

# Build
echo ""
if [ "$LIBRARY_TYPE" == "shared" ]; then
    echo -e "${YELLOW}Compiling libmpv-2.dll...${NC}"
    # Use ninja to build shared library
    ninja -C build libmpv-2.dll

    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Compilation failed${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}Compiling libmpv.a...${NC}"
    # Use ninja to build static library (consistent with official scripts)
    ninja -C build libmpv.a

    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Compilation failed${NC}"
        exit 1
    fi
fi

# Create vendor directory
echo ""
echo -e "${YELLOW}Creating vendor directory...${NC}"
mkdir -p "$VENDOR_DIR/lib"
mkdir -p "$VENDOR_DIR/include"

# Copy library files
echo ""
echo -e "${YELLOW}Copying library files to vendor directory...${NC}"

if [ "$LIBRARY_TYPE" == "shared" ]; then
    # Shared library mode: copy DLL
    LIBMPV_DLL="$BUILD_DIR/libmpv-2.dll"

    if [ -f "$LIBMPV_DLL" ]; then
        cp "$LIBMPV_DLL" "$VENDOR_DIR/lib/libmpv-2.dll"
        echo -e "${GREEN}  Copied libmpv-2.dll${NC}"

        # Show file info
        FILE_SIZE=$(du -h "$LIBMPV_DLL" | cut -f1)
        echo -e "${GRAY}  File size: $FILE_SIZE${NC}"

        # Use MinGW tools to generate import library (for MinGW/Clang built DLLs)
        echo ""
        echo -e "${YELLOW}Generating import library libmpv.lib (for MSVC)...${NC}"

        # Delete old import libraries
        [ -f "$VENDOR_DIR/lib/libmpv.lib" ] && rm -f "$VENDOR_DIR/lib/libmpv.lib"
        [ -f "$VENDOR_DIR/lib/libmpv.def" ] && rm -f "$VENDOR_DIR/lib/libmpv.def"

        # Check if MinGW tools are available
        if command -v gendef >/dev/null 2>&1 && command -v dlltool >/dev/null 2>&1; then
            echo -e "${GRAY}  Using MinGW tools to generate import library...${NC}"

            # Switch to lib directory
            cd "$VENDOR_DIR/lib" || exit 1

            # Step 1: Use gendef to generate .def file
            gendef libmpv-2.dll >/dev/null 2>&1
            if [ -f "libmpv-2.def" ]; then
                mv libmpv-2.def libmpv.def
                echo -e "${GRAY}  Generated .def file${NC}"
            else
                echo -e "${YELLOW}  gendef failed to generate .def file${NC}"
            fi

            # Step 2: Use dlltool to generate import library
            if [ -f "libmpv.def" ]; then
                dlltool -d libmpv.def -l libmpv.lib -D libmpv-2.dll >/dev/null 2>&1
                if [ $? -eq 0 ] && [ -f "libmpv.lib" ]; then
                    echo -e "${GREEN}  Generated libmpv.lib (using MinGW tools)${NC}"
                else
                    echo -e "${YELLOW}  dlltool failed to generate import library${NC}"
                fi
            fi

            cd - >/dev/null || exit 1
        else
            echo -e "${YELLOW}  MinGW tools (gendef/dlltool) not found${NC}"
            echo -e "${GRAY}  Trying MSVC lib.exe...${NC}"

            # Fallback to MSVC lib.exe method
            LIB_EXE=""
            for base in "/c/Program Files/Microsoft Visual Studio/2022/Community" \
                        "/c/Program Files/Microsoft Visual Studio/2022/BuildTools" \
                        "/c/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools" \
                        "/c/Program Files/Microsoft Visual Studio/2019/Community" \
                        "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community"; do
                [ ! -d "$base" ] && continue
                cand=$(find "$base" -name "lib.exe" -path "*/Hostx64/x64/*" 2>/dev/null | head -1)
                if [ -n "$cand" ] && [ -f "$cand" ]; then
                    LIB_EXE="$cand"
                    break
                fi
            done

            if [ -n "$LIB_EXE" ]; then
                DLL_PATH_WIN=$(cygpath -w "$VENDOR_DIR/lib/libmpv-2.dll" 2>/dev/null || echo "$VENDOR_DIR/lib/libmpv-2.dll" | sed 's|^/\([a-z]\)/|\1:\\|; s|/|\\|g')
                LIB_PATH_WIN=$(cygpath -w "$VENDOR_DIR/lib/libmpv.lib" 2>/dev/null || echo "$VENDOR_DIR/lib/libmpv.lib" | sed 's|^/\([a-z]\)/|\1:\\|; s|/|\\|g')

                set +e
                "$LIB_EXE" /DEF:"$DLL_PATH_WIN" /OUT:"$LIB_PATH_WIN" /MACHINE:X64 /NAME:libmpv-2.dll >/dev/null 2>&1
                if [ $? -eq 0 ] && [ -f "$VENDOR_DIR/lib/libmpv.lib" ]; then
                    echo -e "${GREEN}  Generated libmpv.lib (using MSVC lib.exe)${NC}"
                else
                    echo -e "${YELLOW}  MSVC lib.exe generation failed${NC}"
                    echo -e "${GRAY}  Hint: Install MinGW tools in MSYS2: pacman -S mingw-w64-clang-x86_64-tools${NC}"
                fi
                set -e
            else
                echo -e "${YELLOW}  lib.exe not found${NC}"
                echo -e "${GRAY}  Hint: In MSYS2 run: cd vendor/mpv/win32-x64/lib && gendef libmpv-2.dll && dlltool -d libmpv-2.def -l libmpv.lib -D libmpv-2.dll${NC}"
            fi
        fi
    else
        echo -e "${RED}  Error: libmpv-2.dll does not exist${NC}"
        exit 1
    fi
else
    # Static library mode: copy .a file and rename to .lib
    LIBMPV_A="$BUILD_DIR/libmpv.a"

    if [ -f "$LIBMPV_A" ]; then
        # Windows uses .lib extension
        cp "$LIBMPV_A" "$VENDOR_DIR/lib/libmpv.lib"
        echo -e "${GREEN}  Copied libmpv.lib${NC}"

        # Show file info
        FILE_SIZE=$(du -h "$LIBMPV_A" | cut -f1)
        echo -e "${GRAY}  File size: $FILE_SIZE${NC}"
    else
        echo -e "${RED}  Error: libmpv.a does not exist${NC}"
        exit 1
    fi
fi

# Copy header files
echo ""
echo -e "${YELLOW}Copying header files...${NC}"
MPV_INCLUDE_SRC="$MPV_DIR/include/mpv"
MPV_INCLUDE_DST="$VENDOR_DIR/include/mpv"

if [ -d "$MPV_INCLUDE_SRC" ]; then
    if [ -d "$MPV_INCLUDE_DST" ]; then
        rm -rf "$MPV_INCLUDE_DST"
    fi
    mkdir -p "$VENDOR_DIR/include"
    cp -r "$MPV_INCLUDE_SRC" "$VENDOR_DIR/include/"
    echo -e "${GREEN}  Copied header files${NC}"
else
    echo -e "${YELLOW}  Warning: Header file directory does not exist${NC}"
fi

# Copy dynamic link libraries (DLLs)
echo ""
echo -e "${YELLOW}Copying dynamic link libraries (DLLs)...${NC}"

# --local-deps mode: recursively collect libmpv actual dependency DLLs
if [ "$USE_LOCAL_DEPS" == true ] && [ -d "$LOCAL_DEPS_DIR" ]; then
    echo -e "${GREEN}Using locally built dependencies (minimal)${NC}"

    # DLL search paths: prefer local build, then MSYS2 system
    DLL_SEARCH_DIRS=("$LOCAL_DEPS_DIR/bin" "$LOCAL_DEPS_DIR/lib" "$MSYSTEM_PREFIX/bin")

    # Windows system DLLs do not need collection
    is_system_dll() {
        local name="${1,,}"  # convert to lowercase
        case "$name" in
            kernel32.dll|user32.dll|gdi32.dll|advapi32.dll|shell32.dll|\
            ole32.dll|oleaut32.dll|ntdll.dll|ws2_32.dll|wsock32.dll|\
            msvcrt.dll|msvcp*.dll|vcruntime*.dll|ucrtbase.dll|\
            imm32.dll|dwmapi.dll|opengl32.dll|version.dll|shcore.dll|\
            uxtheme.dll|avrt.dll|comctl32.dll|comdlg32.dll|winmm.dll|\
            crypt32.dll|wldap32.dll|secur32.dll|shlwapi.dll|bcrypt.dll|\
            dbghelp.dll|setupapi.dll|cfgmgr32.dll|powrprof.dll|\
            dxgi.dll|d3d11.dll|d3d9.dll|d3dcompiler_*.dll|\
            dwrite.dll|avicap32.dll|mfplat.dll|mf.dll|mfreadwrite.dll|\
            api-ms-win-*.dll|ext-ms-*.dll) return 0 ;;
            *) return 1 ;;
        esac
    }

    # Find DLL file
    find_dll() {
        local name="$1"
        for dir in "${DLL_SEARCH_DIRS[@]}"; do
            if [ -f "$dir/$name" ]; then
                echo "$dir/$name"
                return 0
            fi
        done
        return 1
    }

    # Recursively collect dependencies
    declare -A COLLECTED_DLLS
    collect_deps() {
        local dll_path="$1"
        local dll_name
        dll_name=$(basename "$dll_path")
        local dll_lower="${dll_name,,}"

        # Skip already processed or system DLLs
        [ -n "${COLLECTED_DLLS[$dll_lower]:-}" ] && return
        is_system_dll "$dll_name" && return
        COLLECTED_DLLS[$dll_lower]="$dll_path"

        # Read this DLL's dependencies (only match indented DLL names, exclude metadata lines like File:)
        local deps
        deps=$(llvm-readobj --needed-libs "$dll_path" 2>/dev/null | grep -E '^\s+\S+\.dll$' | sed 's/^[[:space:]]*//' || true)
        for dep in $deps; do
            local dep_lower="${dep,,}"
            [ -n "${COLLECTED_DLLS[$dep_lower]:-}" ] && continue
            is_system_dll "$dep" && continue
            local dep_path
            dep_path=$(find_dll "$dep") || true
            if [ -n "$dep_path" ]; then
                collect_deps "$dep_path"
            else
                echo -e "${YELLOW}  Not found: $dep${NC}"
            fi
        done
    }

    # Start recursive collection from libmpv-2.dll
    collect_deps "$VENDOR_DIR/lib/libmpv-2.dll"

    # Copy collected DLLs
    DLL_COUNT=0
    for dll_lower in $(echo "${!COLLECTED_DLLS[@]}" | tr ' ' '\n' | sort); do
        dll_path="${COLLECTED_DLLS[$dll_lower]}"
        dll_name=$(basename "$dll_path")
        # libmpv-2.dll already copied
        [ "$dll_name" = "libmpv-2.dll" ] && continue
        cp "$dll_path" "$VENDOR_DIR/lib/" 2>/dev/null && {
            fsize=$(du -h "$dll_path" | cut -f1)
            echo -e "${GREEN}  $dll_name${NC} ${GRAY}($fsize)${NC}"
            DLL_COUNT=$((DLL_COUNT + 1))
        }
    done

    # CLANG64 C++ runtime
    for rt_dll in libc++.dll libunwind.dll; do
        if [ -f "$MSYSTEM_PREFIX/bin/$rt_dll" ] && [ ! -f "$VENDOR_DIR/lib/$rt_dll" ]; then
            cp "$MSYSTEM_PREFIX/bin/$rt_dll" "$VENDOR_DIR/lib/" 2>/dev/null && {
                echo -e "${GREEN}  $rt_dll (runtime)${NC}"
                DLL_COUNT=$((DLL_COUNT + 1))
            }
        fi
    done
    echo -e "${GREEN}  Total $DLL_COUNT dependency DLLs (minimal build)${NC}"
else
# Original logic: copy DLLs from MSYS2 system packages (full version, larger size)

# MSYS2 DLL directory
MSYS2_BIN_DIR="$MSYSTEM_PREFIX/bin"
if [ ! -d "$MSYS2_BIN_DIR" ]; then
    # Try other possible paths
    if [ "$MSYSTEM" == "UCRT64" ]; then
        MSYS2_BIN_DIR="/ucrt64/bin"
    elif [ "$MSYSTEM" == "CLANG64" ]; then
        MSYS2_BIN_DIR="/clang64/bin"
    elif [ "$MSYSTEM" == "MINGW64" ]; then
        MSYS2_BIN_DIR="/mingw64/bin"
    else
        MSYS2_BIN_DIR="/usr/bin"
    fi
fi

if [ -d "$MSYS2_BIN_DIR" ]; then
    echo -e "${GRAY}  Search directory: $MSYS2_BIN_DIR${NC}"

    # List of DLL files to copy (FFmpeg and related dependencies)
    DLL_PATTERNS=(
        "avcodec-*.dll"
        "avformat-*.dll"
        "avutil-*.dll"
        "avfilter-*.dll"
        "swscale-*.dll"
        "swresample-*.dll"
        "libplacebo-*.dll"
        "libass-*.dll"
        "luajit-*.dll"
        "luajit.dll"
        "libjpeg-*.dll"
        "libjpeg-turbo-*.dll"
        "zlib*.dll"
        "libpng*.dll"
        "harfbuzz-*.dll"
        "freetype-*.dll"
        "fribidi-*.dll"
        "fontconfig-*.dll"
        "expat-*.dll"
        "bz2-*.dll"
        "lzma-*.dll"
        "zstd-*.dll"
        "vulkan-1.dll"
        "libvulkan-*.dll"
    )

    DLL_COUNT=0
    TOTAL_PATTERNS=${#DLL_PATTERNS[@]}
    PATTERN_INDEX=0

    # Temporarily disable set -e to avoid loop errors causing script exit
    set +e

    for pattern in "${DLL_PATTERNS[@]}"; do
        ((PATTERN_INDEX++))
        echo -e "${GRAY}  [$PATTERN_INDEX/$TOTAL_PATTERNS] Searching: $pattern${NC}"

        # Use find command to locate matching files
        # Store results in temporary variable to avoid subshell issues
        found_dlls=$(find "$MSYS2_BIN_DIR" -maxdepth 1 -name "$pattern" -type f 2>/dev/null)

        if [ -n "$found_dlls" ]; then
            for dll in $found_dlls; do
                if [ -f "$dll" ]; then
                    DLL_NAME=$(basename "$dll")
                    if cp "$dll" "$VENDOR_DIR/lib/" 2>/dev/null; then
                        echo -e "${GREEN}      Copied $DLL_NAME${NC}"
                        DLL_COUNT=$((DLL_COUNT + 1))
                    else
                        echo -e "${YELLOW}      Copy failed: $DLL_NAME${NC}"
                    fi
                fi
            done
        fi
    done

    # Restore set -e
    set -e

    if [ $DLL_COUNT -eq 0 ]; then
        echo -e "${YELLOW}  Warning: No DLL files found (dependencies may be statically linked)${NC}"
        echo -e "${GRAY}  Hint: If libmpv.a is fully static, no DLLs are needed${NC}"
    else
        echo -e "${GREEN}  Copied $DLL_COUNT DLL files to $VENDOR_DIR/lib/${NC}"

        # Check recursive dependencies
        echo ""
        echo -e "${YELLOW}Checking recursive dependencies...${NC}"

        # Temporarily disable set -e
        set +e

        # List of already processed DLLs (avoid duplicates)
        processed_dlls=()
        new_dlls=($(ls "$VENDOR_DIR/lib"/*.dll 2>/dev/null | xargs -n1 basename))

        # Recursively check dependencies (max 5 levels)
        max_depth=5
        depth=0

        # Common dependency libraries (may be needed by libass etc.)
        common_deps=(
            "freetype-*.dll"
            "fribidi-*.dll"
            "fontconfig-*.dll"
            "harfbuzz-*.dll"
            "expat-*.dll"
            "brotlicommon-*.dll"
            "brotlidec-*.dll"
            "brotlienc-*.dll"
            "graphite2-*.dll"
            "icu*.dll"
        )

        # First try to copy common dependencies
        for pattern in "${common_deps[@]}"; do
            found_deps=$(find "$MSYS2_BIN_DIR" -maxdepth 1 -name "$pattern" -type f 2>/dev/null)
            if [ -n "$found_deps" ]; then
                for dep in $found_deps; do
                    dep_name=$(basename "$dep")
                    if [ ! -f "$VENDOR_DIR/lib/$dep_name" ]; then
                        if cp "$dep" "$VENDOR_DIR/lib/" 2>/dev/null; then
                            echo -e "${GREEN}      Copied common dependency: $dep_name${NC}"
                            DLL_COUNT=$((DLL_COUNT + 1))
                        fi
                    fi
                done
            fi
        done

        # Use tools to check DLL dependencies
        while [ ${#new_dlls[@]} -gt 0 ] && [ $depth -lt $max_depth ]; do
            ((depth++))
            current_dlls=("${new_dlls[@]}")
            new_dlls=()

            for dll_name in "${current_dlls[@]}"; do
                dll_path="$VENDOR_DIR/lib/$dll_name"

                # Check if already processed
                if [[ " ${processed_dlls[@]} " =~ " ${dll_name} " ]]; then
                    continue
                fi
                processed_dlls+=("$dll_name")

                # Method 1: Use objdump to check DLL dependencies
                if command -v objdump &> /dev/null; then
                    deps=$(objdump -p "$dll_path" 2>/dev/null | grep -i "DLL Name:" | awk '{print $3}' | grep -vE "KERNEL32|USER32|GDI32|MSVCRT|MSVCP|API-MS-WIN|api-ms-win|ADVAPI32|SHELL32|OLE32|OLEAUT32|WS2_32" || true)

                    if [ -n "$deps" ]; then
                        # Split dependencies by line and process (avoid using <<<)
                        for dep in $deps; do
                            [ -z "$dep" ] && continue

                            # Check if dependency is in MSYS2 bin directory
                            dep_path="$MSYS2_BIN_DIR/$dep"
                            if [ -f "$dep_path" ]; then
                                # Check if already copied
                                if [ ! -f "$VENDOR_DIR/lib/$dep" ]; then
                                    if cp "$dep_path" "$VENDOR_DIR/lib/" 2>/dev/null; then
                                        echo -e "${GREEN}      Found dependency and copied: $dep (from $dll_name)${NC}"
                                        DLL_COUNT=$((DLL_COUNT + 1))
                                        new_dlls+=("$dep")
                                    fi
                                fi
                            fi
                        done
                    fi
                # Method 2: Use ldd (if available, may not be in MSYS2)
                elif command -v ldd &> /dev/null; then
                    deps=$(ldd "$dll_path" 2>/dev/null | grep "$MSYS2_BIN_DIR" | awk '{print $1}' | sed "s|$MSYS2_BIN_DIR/||" || true)

                    if [ -n "$deps" ]; then
                        # Split dependencies by line and process (avoid using <<<)
                        for dep in $deps; do
                            [ -z "$dep" ] && continue

                            dep_path="$MSYS2_BIN_DIR/$dep"
                            if [ -f "$dep_path" ] && [ ! -f "$VENDOR_DIR/lib/$dep" ]; then
                                if cp "$dep_path" "$VENDOR_DIR/lib/" 2>/dev/null; then
                                    echo -e "${GREEN}      Found dependency and copied: $dep (from $dll_name)${NC}"
                                    DLL_COUNT=$((DLL_COUNT + 1))
                                    new_dlls+=("$dep")
                                fi
                            fi
                        done
                    fi
                fi
            done
        done

        # Restore set -e
        set -e

        if [ $DLL_COUNT -gt 0 ]; then
            echo -e "${GREEN}  Total copied $DLL_COUNT DLL files (including recursive dependencies)${NC}"
        fi

        # Verify dependency completeness (minimal: progress + pre-built list, avoid nested loops slowing down)
        echo ""
        echo -e "${YELLOW}Verifying dependency completeness...${NC}"
        if [ -n "${SKIP_DLL_VERIFY:-}" ]; then
            echo -e "${GRAY}  Skipped (SKIP_DLL_VERIFY=1)${NC}"
        elif ! command -v objdump &> /dev/null; then
            echo -e "${GRAY}  Skipped (no objdump)${NC}"
        else
            set +e
            existing_lower=""
            for f in "$VENDOR_DIR/lib"/*.dll; do
                [ -f "$f" ] || continue
                existing_lower="$existing_lower $(basename "$f" | tr '[:upper:]' '[:lower:]')"
            done
            system_pat="KERNEL32|KERNELBASE|ntdll|USER32|GDI32|GDIplus|MSVCRT|MSVCP|VCRUNTIME|API-MS-WIN|api-ms-win|ADVAPI32|SHELL32|OLE32|OLEAUT32|WS2_32|WSOCK32|WINMM|RPCRT4|bcrypt|CRYPT32|ncrypt|DWrite|USP10|DNSAPI|IPHLPAPI|SHLWAPI|VERSION|CFGMGR32|MSIMG32"
            missing_deps=()
            dll_list=("$VENDOR_DIR/lib"/*.dll)
            total_dlls=${#dll_list[@]}
            idx=0
            for dll_file in "${dll_list[@]}"; do
                [ -f "$dll_file" ] || continue
                ((idx++))
                dll_name=$(basename "$dll_file")
                printf "\r  ${GRAY}[%d/%d] %s${NC}   " "$idx" "$total_dlls" "$dll_name"
                deps=$(objdump -p "$dll_file" 2>/dev/null | grep -i "DLL Name:" | awk '{print $3}' || true)
                [ -n "$deps" ] || continue
                for dep in $deps; do
                    [ -n "$dep" ] || continue
                    dep_upper=$(echo "$dep" | tr '[:lower:]' '[:upper:]')
                    [[ "$dep_upper" =~ $system_pat ]] && continue
                    [ -f "$VENDOR_DIR/lib/$dep" ] && continue
                    if [ -f "$MSYS2_BIN_DIR/$dep" ]; then
                        if cp "$MSYS2_BIN_DIR/$dep" "$VENDOR_DIR/lib/" 2>/dev/null; then
                            echo ""
                            echo -e "${GREEN}      Added missing dependency: $dep (required by $dll_name)${NC}"
                            DLL_COUNT=$((DLL_COUNT + 1))
                            existing_lower="$existing_lower $(echo "$dep" | tr '[:upper:]' '[:lower:]')"
                        else
                            missing_deps+=("$dep (required by $dll_name)")
                        fi
                    else
                        dep_lower=$(echo "$dep" | tr '[:upper:]' '[:lower:]')
                        [[ " $existing_lower " == *" $dep_lower "* ]] && continue
                        missing_deps+=("$dep (required by $dll_name)")
                    fi
                done
            done
            echo ""
            printf "\r  ${GRAY}%*s${NC}\r" 60 " "
            if [ ${#missing_deps[@]} -gt 0 ]; then
                echo -e "${YELLOW}  Possibly missing dependencies:${NC}"
                for dep in "${missing_deps[@]}"; do echo -e "${GRAY}      - $dep${NC}"; done
                echo -e "${GRAY}  (Most are system libraries already filtered, generally ignorable)${NC}"
            else
                echo -e "${GREEN}  Dependency check complete${NC}"
            fi
        fi
        set -e
        final_count=$(ls "$VENDOR_DIR/lib"/*.dll 2>/dev/null | wc -l)
        echo ""
        echo -e "${CYAN}Final DLL statistics:${NC}"
        echo -e "${GRAY}  Copied DLL files: $final_count${NC}"
        echo -e "${GRAY}  Location: $VENDOR_DIR/lib/${NC}"
    fi
else
    echo -e "${YELLOW}  Warning: MSYS2 bin directory not found: $MSYS2_BIN_DIR${NC}"
    echo -e "${GRAY}  Hint: Please manually copy the required DLL files to $VENDOR_DIR/lib/${NC}"
fi

fi  # end of local-deps vs MSYS2 branching

# ============================================================
# Strip DLL — remove debug symbols, reduce size
# ============================================================
echo ""
echo -e "${YELLOW}Strip DLLs (removing debug symbols)...${NC}"
if command -v strip &> /dev/null; then
    strip_count=0
    strip_saved=0
    for dll in "$VENDOR_DIR/lib"/*.dll; do
        [ -f "$dll" ] || continue
        before=$(stat -c%s "$dll" 2>/dev/null || wc -c < "$dll" | tr -d ' ')
        strip --strip-unneeded "$dll" 2>/dev/null || true
        after=$(stat -c%s "$dll" 2>/dev/null || wc -c < "$dll" | tr -d ' ')
        if [ "$before" -gt "$after" ]; then
            diff_kb=$(( (before - after) / 1024 ))
            [ "$diff_kb" -gt 100 ] && echo -e "${GREEN}  $(basename "$dll"): -${diff_kb}KB${NC}"
            strip_saved=$((strip_saved + before - after))
        fi
        strip_count=$((strip_count + 1))
    done
    echo -e "${GREEN}  Stripped $strip_count DLLs, saved $((strip_saved / 1024 / 1024))MB total${NC}"
else
    echo -e "${YELLOW}  strip command not available, skipping${NC}"
fi

# Report final size
echo ""
echo -e "${CYAN}Final DLL size:${NC}"
final_size=$(du -sh "$VENDOR_DIR/lib/" 2>/dev/null | cut -f1)
echo -e "${GRAY}  $final_size  $VENDOR_DIR/lib/${NC}"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Build complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "${CYAN}Library location:${NC}"
if [ "$LIBRARY_TYPE" == "shared" ]; then
    echo -e "${GRAY}  Shared library: $VENDOR_DIR/lib/libmpv-2.dll${NC}"
    echo -e "${GRAY}  Import library: $VENDOR_DIR/lib/libmpv.lib (if generated)${NC}"
    echo -e "${GRAY}  Header files: $VENDOR_DIR/include/mpv/${NC}"
    echo ""
    echo -e "${CYAN}Next steps:${NC}"
    echo -e "${GRAY}  1. Build native module: npm run build:native${NC}"
    echo -e "${GRAY}  2. Run dev mode: npm run dev${NC}"
    echo -e "${GRAY}  (If lib.exe was not found, run native/generate_mpv_import_lib.ps1 first to generate import library)${NC}"
else
    echo -e "${GRAY}  Static library: $VENDOR_DIR/lib/libmpv.lib${NC}"
    echo -e "${GRAY}  Header files: $VENDOR_DIR/include/mpv/${NC}"
    echo ""
    echo -e "${CYAN}Next steps:${NC}"
    echo -e "${GRAY}  1. Build native module: npm run build:native${NC}"
    echo -e "${GRAY}  2. Run dev mode: npm run dev${NC}"
fi
echo ""
echo -e "${CYAN}Size optimization tips:${NC}"
echo -e "${GRAY}  Currently using MSYS2 system packages, DLL size is larger (~178MB).${NC}"
echo -e "${GRAY}  To significantly reduce size (~50MB), build dependencies from source:${NC}"
echo -e "${GRAY}    1. ./build_deps_windows.sh          # Build all dependencies from source${NC}"
echo -e "${GRAY}    2. ./build_mpv_windows_msys2.sh --shared --local-deps  # Use local dependencies${NC}"
echo ""
